# Generated by Django 6.0 on 2025-12-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='janri',
            field=models.CharField(default=1, max_length=101),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default=2, max_length=101),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0),
        ),
    ]
